# app/abuse_types.py
abuse_types = {
    "fr": {
        "abuse_of_power": "Abus de pouvoir",
        "procedural_delay": "Retards procéduraux",
        "administrative_corruption": "Corruption administrative",
        "extortion": "Extorsion",
        "judicial_discrimination": "Discrimination judiciaire",
        "medical_neglect": "Négligence médicale",
        "obstruction_of_justice": "Entrave à la justice",
        "other_abuses": "Autres abus",
    },
    "es": {
        "abuse_of_power": "Abuso de poder",
        "procedural_delay": "Demoras procesales",
        "administrative_corruption": "Corrupción administrativa",
        "extortion": "Extorsión",
        "judicial_discrimination": "Discriminación judicial",
        "medical_neglect": "Negligencia médica",
        "obstruction_of_justice": "Obstrucción de la justicia",
        "other_abuses": "Otros abusos",
    },
    "en": {
        "abuse_of_power": "Abuse of power",
        "procedural_delay": "Procedural delays",
        "administrative_corruption": "Administrative corruption",
        "extortion": "Extortion",
        "judicial_discrimination": "Judicial discrimination",
        "medical_neglect": "Medical neglect",
        "obstruction_of_justice": "Obstruction of justice",
        "other_abuses": "Other abuses",
    },
    "sw": {
        "abuse_of_power": "Matumizi mabaya ya mamlaka",
        "procedural_delay": "Kucheleweshwa kwa mchakato",
        "administrative_corruption": "Ufisadi wa kiutawala",
        "extortion": "Utozaji wa rushwa/udhalimu wa fedha",
        "judicial_discrimination": "Ubaguzi wa kimahakama",
        "medical_neglect": "Kupuuza huduma za afya",
        "obstruction_of_justice": "Kuzuia haki",
        "other_abuses": "Madhara mengine",
    },
    "ln": {
        "abuse_of_power": "Kosalelaka makasi na botosi te",
        "procedural_delay": "Nkɔkɔ ya procédure",
        "administrative_corruption": "Kokɔrɔpɔ ya administration",
        "extortion": "Kosɛnga mbongo na makasi",
        "judicial_discrimination": "Diskriminasyon ya bosambisi",
        "medical_neglect": "Koboya kosalela nsango ya santé",
        "obstruction_of_justice": "Kobangisa bosambisi",
        "other_abuses": "Babus mosusu",
    },
}
